### PR TITLE
Don't remove the fopm file.

### PR DESCRIPTION
**Pull request by LifeAsStranger**
This is owned by Camzie99 and only Camzie99. So you have no right to remove someone else commands.

### CODE REVIEW

**Comment by AlphaGaming** [comment]
Objection, He does't code the commands any more

**Comment by LifeAsStranger** [comment]
@AlphaGaming, well, it looks like DMCA is coming to your way.

@CameronRedmore, if you please?

**Comment by CameronRedmore** [comment]
Whilst I may not maintain the plugin any longer, the license still stands which clearly states:

Extra Terms
In the event you do use the FreedomOpMod: Remastered; you may not then remove any creditation to Camzie99 or Cameron B. R. Redmore and you may not remove or modify the Command_fopm.java.

I kindly request the command is re-added or I shall be forced to take drastic measures. Also, I now have a new plugin instead of the FOPM: R which you can get details on over at http://fop.us.to/index.php?threads/amethystfreedommod.1368/

**Comment by AlexFreedomMod** [comment]
Merging to prevent copyright claim.

**Pull request merged**
