### PR TITLE
Added new Donator system

### PR DESCRIPTION
**Pull request by LifeAsStranger**
Still working on the API.

### CODE REVIEW

**Comment by AlexFreedomMod** [comment]
Looking pretty good

**Comment by LifeAsStranger** [comment]
@AlexFreedomMod, if you don't mind, can you add me to this repo so I can save my API to different branch then merge it when completed...

**Comment by AlexFreedomMod** [comment]
Sure

**Comment by LifeAsStranger** [comment]
Still don't have access to do anything

**Comment by AlexFreedomMod** [comment]
Fizing

**Pull request merged**
